# UV Global Configuration for WasTask
# This file contains UV-specific settings

# Python version preference
python-preference = "only-managed"

# Cache configuration
cache-dir = ".uv-cache"

# Install configuration
link-mode = "copy"
compile-bytecode = true

# Index configuration
index-url = "https://pypi.org/simple"

# Concurrent operations for speed
concurrent-downloads = 8
concurrent-builds = 4
concurrent-installs = 4

# Preview features (if available)
preview = true