version: '3.8'

services:
  wastask-api:
    image: python:3.11-slim
    command: >
      bash -c "
      pip install fastapi uvicorn &&
      python -c 'from fastapi import FastAPI; import uvicorn; app = FastAPI(title=\"WasTask API\"); app.get(\"/\")(lambda: {\"message\": \"WasTask funcionando na VPS!\", \"status\": \"online\"}); app.get(\"/health\")(lambda: {\"status\": \"healthy\"}); app.get(\"/api/v1/projects/\")(lambda: {\"projects\": []}); uvicorn.run(app, host=\"0.0.0.0\", port=8000)'
      "
    networks:
      - WasNet
    deploy:
      restart_policy:
        condition: any
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=WasNet"
        - "traefik.http.routers.wastask.rule=Host(`wastasks.wastintas.com.br`)"
        - "traefik.http.routers.wastask.entrypoints=websecure"
        - "traefik.http.routers.wastask.tls=true"
        - "traefik.http.routers.wastask.tls.certresolver=letsencrypt"
        - "traefik.http.services.wastask.loadbalancer.server.port=8000"

networks:
  WasNet:
    external: true