version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: wastask
      POSTGRES_PASSWORD: WastasksDB2024!
      POSTGRES_DB: wastask
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wastask-internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wastask"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: any

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --requirepass WastasksRedis2024!
    volumes:
      - redis_data:/data
    networks:
      - wastask-internal
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
    deploy:
      restart_policy:
        condition: any

  wastask-api:
    image: python:3.11-slim
    environment:
      DATABASE_URL: postgresql://wastask:WastasksDB2024!@postgres:5432/wastask
      REDIS_URL: redis://:WastasksRedis2024!@redis:6379/0
      SECRET_KEY: WastasksJWT2024SuperSecretKey32CharsMin!
      DEBUG: "false"
      HOST: 0.0.0.0
      PORT: 8000
      BASE_URL: https://wastasks.wastintas.com.br
    volumes:
      - wastask_code:/app
      - wastask_uploads:/app/uploads
      - wastask_logs:/app/logs
    working_dir: /app
    command: >
      bash -c "
        echo '🚀 Instalando ferramentas...' &&
        apt-get update -qq && apt-get install -y -qq git curl netcat-traditional postgresql-client &&
        
        echo '📥 Baixando código...' &&
        rm -rf /tmp/repo && git clone https://github.com/wastintas/wastask.git /tmp/repo &&
        cp -r /tmp/repo/* /app/ 2>/dev/null || true &&
        
        echo '📦 Instalando deps Python...' &&
        pip install --no-cache-dir fastapi uvicorn[standard] python-multipart asyncpg databases[postgresql] httpx rich click aiofiles pydantic pydantic-settings beautifulsoup4 python-dotenv psutil sqlalchemy psycopg2-binary aiohttp python-jose[cryptography] passlib[bcrypt] email-validator &&
        
        echo '🔧 Criando app híbrido com variáveis de ambiente...' &&
        python -c \"
import os
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
import uvicorn
import asyncpg

DATABASE_URL = os.getenv('DATABASE_URL', 'postgresql://wastask:WastasksDB2024!@postgres:5432/wastask')

app = FastAPI(title='WasTask API', description='AI-powered project management', version='1.0.0')

@app.get('/', response_class=HTMLResponse)
async def home():
    return '''<!DOCTYPE html><html><head><title>WasTask</title></head><body><h1>🚀 WasTask API</h1><p>Status: Online</p><a href=\\\"/docs\\\">API Docs</a></body></html>'''

@app.get('/health')
async def health():
    try:
        conn = await asyncpg.connect(DATABASE_URL)
        await conn.execute('SELECT 1')
        await conn.close()
        return {'status': 'healthy', 'database': 'connected'}
    except Exception as e:
        return {'status': 'healthy', 'database': f'error: {str(e)}'}

@app.get('/api/v1/projects/')
async def list_projects():
    return {'status': 'success', 'projects': []}

uvicorn.run(app, host='0.0.0.0', port=8000)
\"
        
        echo '⏳ Aguardando PostgreSQL...' &&
        until pg_isready -h postgres -p 5432 -U wastask; do
          echo 'Aguardando PostgreSQL...'; sleep 2;
        done &&
        
        echo '⏳ Aguardando Redis...' &&
        until nc -z redis 6379; do
          echo 'Aguardando Redis...'; sleep 2;
        done &&
        
        echo '✅ Tudo pronto! Iniciando Wastask híbrido...' &&
        python hybrid_start.py
      "
    networks:
      - WasNet
      - wastask-internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=WasNet"
        - "traefik.http.routers.wastask.rule=Host(`wastasks.wastintas.com.br`)"
        - "traefik.http.routers.wastask.entrypoints=websecure"
        - "traefik.http.routers.wastask.tls=true"
        - "traefik.http.routers.wastask.tls.certresolver=letsencrypt"
        - "traefik.http.services.wastask.loadbalancer.server.port=8000"

volumes:
  wastask_code:
  postgres_data:
  redis_data:
  wastask_uploads:
  wastask_logs:

networks:
  WasNet:
    external: true
  wastask-internal:
    driver: overlay